Feat: Create Notification Entry Form
hyperjumptech/monika-config-generator pull request #29
Opened 2021-04-12 08:01 UTC by haricnugraha

### What does this PR solve?
Create notification entry form. Resolves #7 

### How do you implement this?
![Notification SMTP](https://user-images.githubusercontent.com/15191978/114360667-7d58a980-9b9f-11eb-86f9-e44fbab73df7.png)
![Notification Mailgun](https://user-images.githubusercontent.com/15191978/114360676-7f226d00-9b9f-11eb-8b68-3cfadb3aa936.png)

### How do I test this?
1. Run `npm run dev`
2. Open localhost:3000 in browser

2021-04-12 08:35 UTC, nicnocquee requested changes
In notifications.tsx:

1. for telephone number, use `<input type="tel">` instead of `number`
2. i don't thinks there is `type="apiKey"`. maybe just remove it, or change to `text`.
3. i don't thinks there is `type="domain"`. maybe just remove it, or change to `text`.

2021-04-12 10:16 UTC, haricnugraha commented
> In notifications.tsx:
> 
> 1. for telephone number, use `<input type="tel">` instead of `number`
> 2. i don't thinks there is `type="apiKey"`. maybe just remove it, or change to `text`.
> 3. i don't thinks there is `type="domain"`. maybe just remove it, or change to `text`.

Fixed, please recheck.

2021-04-13 07:57 UTC, nicnocquee approved these changes

2021-04-13 08:07 UTC, raosan approved these changes

2021-04-13 08:13 UTC, armedi approved these changes

2021-04-13 08:21 UTC, merged