chore: add tests
hyperjumptech/monika-config-generator pull request #71
Opened 2021-05-11 13:32 UTC by samsunoor

implement #62 by adding tests for the components

- `npm run test` to run the tests
- `npm run test:coverage` for the coverage report

2021-05-12 05:58 UTC, haricnugraha approved these changes

2021-05-17 07:16 UTC, dennypradipta requested changes

2021-05-17 07:16 UTC, dennypradipta commented on __tests__/index.test.tsx
> +import { render, fireEvent, screen, waitFor } from '@testing-library/react';
Small task, please remove unused variable as pointed by Github Actions

2021-05-17 07:58 UTC, dennypradipta commented
I forgot one thing: Now that we have the test configured, could you please add a new job in Github action workflow to run the npm run test after running `npm run static-analysis`?

2021-05-17 08:02 UTC, dennypradipta approved these changes

2021-05-17 08:02 UTC, merged