Revamp UI
hyperjumptech/monika-config-generator pull request #80
Opened 2021-08-04 10:46 UTC by samsunoor

This PR resolves #79 

### How to test
- `npm run dev`
- Visit localhost:3000

2021-08-04 11:01 UTC, dennypradipta requested changes

2021-08-04 11:01 UTC, dennypradipta commented on components/header/index.tsx
> +                <span className="ml-2 px-3 py-2 flex items-center text-white font-sans underline font-bold leading-snug hover:opacity-75">
![image](https://user-images.githubusercontent.com/16670475/128169961-45e4f72e-bc2c-4825-b266-e09b61850858.png)
Even when this is currently active, I think it's better to be clickable and redirect you to the monika config generator index page

2021-08-05 08:21 UTC, gsukanto approved these changes
lgtm

2021-08-05 08:47 UTC, dennypradipta approved these changes

2021-08-05 08:54 UTC, merged